
require 'rubygems'
require 'lib/rake_task_redefine_task.rb'

begin
  gem 'echoe', '>=2.3'
  require 'echoe'

  echoe = Echoe.new("cgi_multipart_eof_fix") do |p|
    p.author = "Evan Weaver" 
    p.rubyforge_name = "mongrel"
    p.summary = p.description = "Fix an exploitable bug in CGI multipart parsing which affects Ruby <= 1.8.5 when multipart boundary attribute contains a non-halting regular expression string."    
    p.url = "http://blog.evanweaver.com/pages/code#cgi_multipart_eof_fix"
    p.docs_host = "blog.evanweaver.com:~/www/snax/public/files/doc/"
    p.rdoc_pattern = /CHANGELOG|LICENSE|README|lib\/cgi_multipart_eof_fix/
    p.need_tar_gz = false
    p.need_tgz = true
  end
            
rescue LoadError
  desc 'Run the default tasks'
  task :default => :test  
end

Rake::Task.redefine_task("test") do
  system "ruby -Ibin:lib:test test/cgi_multipart_eof_fix_test.rb"
end
