
require 'echoe'

Echoe.new("cgi_multipart_eof_fix") do |p|
  p.author = "Evan Weaver" 
  p.rubyforge_name = "mongrel"
  p.summary = p.description = "Fix an exploitable bug in CGI multipart parsing."    
  p.url = "http://blog.evanweaver.com/pages/code#cgi_multipart_eof_fix"
  p.docs_host = "blog.evanweaver.com:~/www/bax/public/files/doc/"
  p.rdoc_pattern = /CHANGELOG|LICENSE|README|lib\/cgi_multipart_eof_fix/

  p.need_tar_gz = false
  p.need_tgz = true
  p.certificate_chain = ['/Users/eweaver/p/configuration/gem_certificates/mongrel/mongrel-public_cert.pem',
    '/Users/eweaver/p/configuration/gem_certificates/evan_weaver-mongrel-public_cert.pem']    
  p.require_signed = true
end

