#!/usr/bin/env ruby

=begin
A simplified test runner; it runs all tests by default.
It assumes that "bundle exec rake compile" has been run.

It can also be passed a glob or test file names.  If multiple test file names
are used, separate them by the File::PATH_SEPARATOR character with no spaces.
The file extension is optional.

Category filters (mutually exclusive with each other; may combine with -v/-w):
  --unit         in-process tests (see test/categories.rb)
  --integration  process-spawn / TestIntegration tests

If arguments are used that take values (eg seed), use the 'no space' version,
like -s33388 or --seed=33388

'-w' is an additional option, it will switch $VERBOSE to true before the
test files are loaded.

'-z' is an additional option, it will switch $VERBOSE to true and cancel the tests.

Finally, to keep the code simple, if you pass an invalid argument for file
filtering it will either error or run minitest with no tests loaded

Examples, run from the top Puma repo folder:
test/runner
test/runner -v
test/runner --unit
test/runner --integration
test/runner -v test_puma_server
test/runner --verbose test_puma_server*
test/runner --verbose test_integration_cluster:test_integration_single
test/runner --verbose test*ssl*

Note that on macOS, globs (using '*') need to be quoted, as in:
test/runner -v 'test_integration_*.rb'
=end

require 'bundler/setup'
require 'stringio'
require_relative 'categories'

if ARGV.delete '-z'
  show_warnings = true
  no_tests = true
elsif ARGV.delete '-w'
  show_warnings = true
elsif ARGV.delete('-wv') || ARGV.delete('-vw')
  show_warnings = true
  ARGV.unshift '-v'
else
  show_warnings = nil
end

unit = ARGV.delete('--unit')
integration = ARGV.delete('--integration')
if unit && integration
  STDERR.puts 'test/runner: use only one of --unit or --integration'
  exit 1
end
if (unit || integration) && !(ARGV.empty? || ARGV.all? { |a| a.start_with?('-') })
  STDERR.puts 'test/runner: --unit/--integration cannot be combined with file name arguments'
  exit 1
end

if show_warnings
  stderr, $stderr = STDERR, StringIO.new
  $VERBOSE = true
end

require 'minitest'

if unit
  PumaTestCategories.unit_basenames(__dir__).each { |tf| require_relative tf }
elsif integration
  PumaTestCategories.integration_basenames.each { |tf| require_relative tf }
elsif ARGV.empty? || ARGV.last.start_with?('-')
  Dir['test_*.rb', base: __dir__].sort.each { |tf| require_relative tf }
else
  file_arg = ARGV.pop.delete_suffix('.rb')
  if file_arg.include? File::PATH_SEPARATOR
    file_args = file_arg.split(File::PATH_SEPARATOR).map { |fn| fn.delete_suffix('.rb') }
    file_args.each { |tf| require_relative "#{tf}.rb" }
  elsif file_arg.include? '*'
    Dir["#{file_arg}.rb", base: __dir__].sort.each { |tf| require_relative tf }
  else
    require_relative "#{file_arg}.rb"
  end
end

if show_warnings
  warnings = $stderr.string&.strip
  $stderr = stderr
  if warnings && !warnings.empty?
    warnings = warnings.gsub("#{__dir__}/", '')
      .split("\n")
      .sort
      .join("\n")
    STDERR.write "#{warnings}\n\n"
  end
end
exit 1 if no_tests

STDOUT.write "Minitest version: #{Minitest::VERSION}\n\n"
