require:
  - rubocop-performance

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  Exclude:
    - 'tmp/**/*'
    - '.bundle/**/*'
    - '**/vendor/bundle/**/*'
    - 'examples/**/*'
    - 'pkg/**/*'
    - 'Rakefile'
  SuggestExtensions: false
  NewCops: enable

# enable all Performance cops
Performance:
  Enabled: true

# ————————————————————————————————————————— disabled cops

# ————————————————————————————————————————— enabled cops

# Layout

Layout/AccessModifierIndentation:
  Enabled: true

Layout/IndentationStyle:
  Enabled: true

Layout/SpaceAfterColon:
  Enabled: true

Layout/SpaceAroundKeyword:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceBeforeFirstArg:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  Exclude:
    - 'test/**/*'

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

# Lint

Lint/Debugger:
  Enabled: true

# Metrics

Metrics/ParameterLists:
  Max: 7

# Naming

Naming/ConstantName:
  Enabled: true

Naming/MethodName:
  Enabled: true
  Exclude:
    - 'test/**/**'

Naming/VariableName:
  Enabled: true

# Style

Style/MethodDefParentheses:
  Enabled: true

Style/SafeNavigation:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true
