require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'tools/rakehelp'
require 'fileutils'
include FileUtils

setup_tests
setup_clean ["pkg", "lib/*.bundle", "*.gem", ".config"]

setup_rdoc ['README', 'LICENSE', 'COPYING', 'lib/**/*.rb', 'doc/**/*.rdoc']

desc "Does a full compile, test run"
task :default => [:test, :package]

version="0.1"
name="mongrel_service"

setup_gem(name, version) do |spec|
  spec.summary = "Mongrel Native Win32 Service Plugin"
  spec.description = "This plugin offer native win32 services for rails."
  spec.author="Luis Lavena"
  
  # added mongrel_service executable
  spec.executables = ["mongrel_service"]
  
  spec.add_dependency('gem_plugin', '>= 0.2.1')
  spec.add_dependency('mongrel', '>= 0.3.12.4')
  spec.files += Dir.glob("resources/**/*")
end


task :install => [:test, :package] do
  sh %{sudo gem install pkg/#{name}-#{version}.gem}
end

task :uninstall => [:clean] do
  sh %{sudo gem uninstall #{name}}
end

