require 'echoe'

Echoe.new("gem_plugin") do |p|
  p.author="Zed A. Shaw"
  p.project = "mongrel"
  p.summary = "A plugin system based on rubygems that uses dependencies only"
  p.test_pattern = "test/test_plugins.rb"
  p.dependencies = ["rake >=0.7"]
  p.clean_pattern += ["pkg", "lib/*.bundle", "*.gem", ".config"]
  p.rdoc_pattern = ['README', 'LICENSE', 'COPYING', 'lib/**/*.rb', 'doc/**/*.rdoc']
end

task :site => [:redocs] do
  sh %{ rsync -r doc/* rubyforge.org:/var/www/gforge-projects/mongrel/gem_plugin_rdoc/ }
end
