
require 'echoe'

Echoe.new("gem_plugin") do |p|
  p.author="Zed A. Shaw"
  p.project = "mongrel"
  p.summary = "A plugin system based on rubygems that uses dependencies only"

  p.need_tar_gz = false
  p.need_tgz = true
  p.require_signed = true
  p.certificate_chain = ['/Users/eweaver/p/configuration/gem_certificates/mongrel/mongrel-public_cert.pem',
    '/Users/eweaver/p/configuration/gem_certificates/evan_weaver-mongrel-public_cert.pem']    
  
  p.test_pattern = "test/test_plugins.rb"
  p.clean_pattern += ["pkg", "lib/*.bundle", "*.gem", ".config"]
  p.rdoc_pattern = ['README', 'LICENSE', 'COPYING', 'lib/**/*.rb', 'doc/**/*.rdoc']
end

# The default Echoe rdoc location should be good enough, but it's not what we currently use.
# It would be: rubyforge.org:/var/www/gforge-projects/mongrel/gem_plugin/
#
# task :site => [:redocs] do
#   sh %{ rsync -r doc/* rubyforge.org:/var/www/gforge-projects/mongrel/gem_plugin_rdoc/ }
# end
