require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'tools/rakehelp'
require 'fileutils'
include FileUtils

setup_tests
setup_clean ["pkg", "lib/*.bundle", "*.gem", ".config"]

setup_rdoc ['README', 'LICENSE', 'COPYING', 'lib/**/*.rb', 'doc/**/*.rdoc']

desc "Does a full compile, test run"
task :default => [:test, :package, :gem_test]

version="0.1"
summary = "Mongrel plugin that gives you web based config tool"
test_file = "test/test_config.rb"
author="Zed A. Shaw"
name="mongrel_config"
scripts=[]

setup_gem(name, version,  author, summary, scripts, test_file) do |spec|
  spec.add_dependency('mongrel', '>= 0.3.9')
  spec.add_dependency('gem_plugin', '>= 0.1')
  spec.add_dependency('camping', '>= 1.3')
end


task :gem_test do
  sh %{sudo gem install pkg/mongrel_config-#{version}.gem}
end
