require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'tools/rakehelp'
require 'fileutils'
include FileUtils

setup_tests
setup_clean ["pkg", "lib/*.bundle", "*.gem", ".config"]

setup_rdoc ['README', 'LICENSE', 'COPYING', 'lib/**/*.rb', 'doc/**/*.rdoc']

desc "Does a full compile, test run"
task :default => [:test, :package]

version="0.2"
name="mongrel_config"

setup_gem(name, version) do |spec|
  spec.summary = "Mongrel plugin that gives you web based config tool using Camping"
  spec.description = spec.summary
  spec.test_file = "test/test_config.rb"
  spec.author="Zed A. Shaw"
  spec.add_dependency('mongrel', '>= 0.3.10')
  spec.add_dependency('gem_plugin', '>= 0.1')
  spec.add_dependency('camping', '>= 1.3')
  spec.files += Dir.glob("resources/**/*")
end


task :install => [:test, :package] do
  sh %{sudo gem install pkg/#{name}-#{version}.gem}
end

task :uninstall => [:clean] do
  sh %{sudo gem uninstall #{name}}
end

