require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'tools/rakehelp'
require 'fileutils'
include FileUtils

setup_tests
setup_clean ["pkg", "lib/*.bundle", "*.gem", ".config"]

setup_rdoc ['README', 'LICENSE', 'COPYING', 'lib/**/*.rb', 'doc/**/*.rdoc']

desc "Does a full compile, test run"
task :default => [:test, :package]

version="0.1"
name="mongrel_upload_progress"

setup_gem(name, version) do |spec|
  spec.summary = "The mongrel_upload_progress GemPlugin"
  spec.description = spec.summary
  spec.author="Nobody"
  spec.add_dependency('gem_plugin', '>= 0.2.1')
  spec.files += Dir.glob("resources/**/*")
end


task :install => [:test, :package] do
  sh %{sudo gem install pkg/#{name}-#{version}.gem}
end

task :uninstall => [:clean] do
  sh %{sudo gem uninstall #{name}}
end

