require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'tools/rakehelp'
require 'fileutils'
include FileUtils

setup_tests
setup_clean ["pkg", "lib/*.bundle", "*.gem", ".config"]

setup_rdoc ['README', 'LICENSE', 'COPYING', 'lib/**/*.rb', 'doc/**/*.rdoc']

desc "Does a full compile, test run"
task :default => [:test, :package]

version="0.1"
summary = "A sample plugin that reports the status of mongrel."
test_file = "test/test_empty.rb"
author="Zed A. Shaw"
name="mongrel_status"
scripts=[]

setup_gem(name, version,  author, summary, scripts, test_file) do |spec|
  spec.add_dependency('mongrel', '>= 0.3.9')
  spec.add_dependency('gem_plugin', '>= 0.2')
end

