require 'rake'
require 'rake/testtask'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'tools/rakehelp'
require 'fileutils'
include FileUtils

setup_tests
setup_clean ["pkg", "lib/*.bundle", "*.gem", ".config"]

setup_rdoc ['README', 'LICENSE', 'COPYING', 'lib/**/*.rb', 'doc/**/*.rdoc']

desc "Does a full compile, test run"
task :default => [:test, :package]

version="0.2.2"
name="mongrel_status"

setup_gem(name, version) do |spec|
  spec.summary = "A sample plugin that reports the status of mongrel."
  spec.description = spec.summary
  spec.test_file = "test/test_empty.rb"
  spec.author="Zed A. Shaw"
  spec.add_dependency('mongrel', '>= 0.3.11')
  spec.add_dependency('gem_plugin', '>= 0.2.1')
end

task :install => [:test, :package] do
  sh %{sudo gem install pkg/#{name}-#{version}.gem}
end

task :uninstall => [:clean] do
  sh %{sudo gem uninstall #{name}}
end
