
require 'echoe'

Echoe.new("mongrel_cluster") do |p|
  p.summary = "Mongrel plugin that provides commands and Capistrano tasks for managing multiple Mongrel processes."
  p.project = "mongrel"
  p.author="Bradley Taylor"
  p.dependencies = ['gem_plugin >=0.2.3', 'mongrel >=1.0.2']
  p.has_rdoc = false

  p.need_tar_gz = false
  p.need_tgz = true
  p.require_signed = true
  p.certificate_chain = ['~/p/configuration/gem_certificates/mongrel/mongrel-public_cert.pem',
    '~/p/configuration/gem_certificates/evan_weaver-mongrel-public_cert.pem']    
end

# Is this still used?
task :gem_source do
  mkdir_p "pkg/gems"

  FileList["**/*.gem"].each { |gem| mv gem, "pkg/gems" }
  FileList["pkg/*.tgz"].each {|tgz| rm tgz }
  rm_rf "pkg/#{name}-#{version}"

  sh %{ generate_yaml_index.rb -d pkg }
  sh %{ scp -r pkg/* #{ENV['SSH_USER']}@rubyforge.org:/var/www/gforge-projects/mongrel/releases/ }
end

