
require 'echoe'

Echoe.new("mongrel_experimental") do |p|
  p.summary = "Backports and experimental features for Mongrel."
  p.project = "mongrel"
  p.author="The Mongrel Team"
  p.dependencies = ['mongrel =1.1']
  
  p.need_tar_gz = false
  p.need_tgz = true
  p.certificate_chain = ['~/p/configuration/gem_certificates/mongrel/mongrel-public_cert.pem',
    '~/p/configuration/gem_certificates/evan_weaver-mongrel-public_cert.pem']    
  p.require_signed = true
end
