name: Ensure pull requests are labelled
on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const {data: labels} = await github.rest.issues.listLabelsOnIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            console.log(labels)
            
            const requiredLabels = ["security", "feature", "bug", "perf", "refactor", "maintenance", "docs"]
            const labelsPresent = labels.some((label) => requiredLabels.includes(label.name))
            
            if (!labelsPresent) {
              throw new Error(`All pull requests require at least one of the required labels ${requiredLabels}`)
            }
